make the 'rpm_ci' working outside from travis
- fix issues with umask 0077 Dockerfile
- export PARENT_VERSION in travis_build.sh, the substitution is
  now done in 'rpm_ci' itself
- add 'repo' feature into srpmgen (so we could potentially
  generate pgjdbc-parent-poms from git in future, too)
- use :Z flag for volume for docker run (SELinux)

diff --git a/packaging/rpm/fedora-image/copr-ci-git b/packaging/rpm/fedora-image/copr-ci-git
--- a/packaging/rpm/fedora-image/copr-ci-git
+++ b/packaging/rpm/fedora-image/copr-ci-git
@@ -6,6 +6,15 @@ copr_fe_url=https://copr.fedorainfracloud.org/coprs/g/pgjdbc/pgjdbc-travis/build
 copr_be_link=https://copr-be.cloud.fedoraproject.org/results/@pgjdbc/pgjdbc-travis/fedora-rawhide-x86_64/
 status_file=copr_build_id
 
+missing_variable=false
+for i in PARENT_VERSION; do
+    eval "test -z \"\$$i\"" && {
+        missing_variable=:
+        echo >&2 " ! missing env variable \$$i"
+    }
+done
+$missing_variable && exit 1
+
 copr_wrapper ()
 (
     set +x
@@ -29,7 +38,9 @@ cd "$1"
 git_rev=$(git rev-parse --short=7 HEAD)
 date_rev=$(date +%Y%m%d_%H%M%S)
 release=${date_rev}.git$git_rev
-sed "s!^Release:.*\$!Release: 1.$release%{?dist}!" "$2".spec.tpl > "$2".spec
+sed -e "s!^Release:.*\$!Release: 1.$release%{?dist}!" \
+    -e "s!%global parent_ver.*!%global parent_ver $PARENT_VERSION!" \
+    "$2".spec.tpl > "$2".spec
 srpmgen
 build_local -bs "$2".spec --define "dist %nil"
 copr_wrapper --config "$1"/copr-token build --nowait @pgjdbc/pgjdbc-travis "$2-$3-1.$release.src.rpm"
